---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: mariadb_repo
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: mariadb_server
      become: yes
      yum: name=MariaDB-server,MariaDB-client update_cache=yes state=present

    - name: start_it
      become: yes
      service: name=mariadb state=started enabled=yes

    - name: look_for_it
      template: src=db/mariadb_answers.txt dest=/tmp/mariadb_answers.txt mode=0644

    - name: mysql_install
      become: yes
      shell: /usr/bin/mysql_secure_installation </tmp/mariadb_answers.txt

    - name: search
      unarchive: src=db/db.tgz dest=~/ mode=0755

    - name: make_it
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
